### ISSUE TITLE
Bitbucket Server support?

### ISSUE THREAD

**Issue by captainjapeng** [bitsbeats/drone-tree-config#2]
Is there a way for this to work on Bitbucket Server?

**Comment by foosinn** [comment]
this would require some code changes and some new test.

https://github.com/drone/go-scm can handle all provides that drone uses. 

i you or someone else wants do do the changes, i am happy to merge them.

**Comment by Oduig** [comment]
I forked this repository to attempt the changes myself. I have no previous experience with golang, but it seems like we are going to hit a wall with _go-scm_ because two API calls are missing. That means we have two options.

1. Make a PR for https://github.com/drone/go-scm with implementations for the missing calls for every major repository.
2. Implement the necessary logic as part of this plugin, focus on BitBucket for the moment and add repositories as we go along.


Missing no. 1 is a call to `repos/%s/compare/oldref...newref` to run a diff between two commits. I wonder why we can't just list the changes in the commit, in other words, why don't we just call `repos/%s/compare/newref`?

        changes, _, err := req.Client.Repositories.CompareCommits(ctx, req.Repo.Namespace, req.Repo.Name, before, req.Build.After)

Missing no. 2 is more troublesome, in that the call to `repos/%s/contents/path` accepts directories, but the source code of _go-scm_ [assumes that you're calling it on a file](https://github.com/drone/go-scm/blob/master/scm/driver/github/content.go), causing it to crash because the response has a different format than the one expected. See https://developer.github.com/v3/repos/contents/#get-contents.

    _, ls, _, err := req.Client.Repositories.GetContents(ctx, req.Repo.Namespace, req.Repo.Name, dir, &ref)

I worry that adding the above two API calls to _go-scm_ is going to take a lot of time. Is there anyone that could help with that? Alternatively, would you accept a PR for _drone-tree-config_ that just implements BitBucket support natively in this plugin?

**Comment by foosinn** [comment]
I would be ok with it if we can abstract the provider to an interface. That way it should be easy to add new providers afterwards.

For now we would have just a bitbucket and a github provider. Users that require more would be able to add them.

Thanks for taking the time!

**Comment by Oduig** [comment]
Thanks, I'll do my best to find the time for that. Regarding the first API call, is there a difference between `/compare/oldref...newref` and `/commits/newref`? It seems to me that the content of a commit is by definition the same as the diff with the previous commit, but I might be overlooking something.

(This is assuming that `oldref` is `newref~1`, which seems to always be true in the source code.)

**Comment by foosinn** [comment]
If i remind correctly: if one pushes multiple commits newref~1 and oldref are diffrent.

**Comment by Oduig** [comment]
I managed to extract a common interface and finished an implementation with BitBucket support. I'll test it over the next few days and send a PR.

It's quite a big change due to SCM-specific code having to be separated. It is fully backwards compatible with one exception, I thought it better to rename the `GITHUB_SERVER` variable to `SERVER` rather than making separate versions for each SCM. I have the image up on `jodiug/drone-tree-config`, if anyone would like to test it that would be very helpful!

Options passed to drone for BitBucket support: 

    AUTH_SERVER: https://bitbucket.org
    SERVER: https://api.bitbucket.org
    BITBUCKET_CLIENT: "client_id"
    BITBUCKET_SECRET: "client_secret"

You can use the same credentials as you use for Drone itself.

**Comment by foosinn** [comment]
Hey @Oduig,

awesome! I will habe a detailed look and test against our infrastructure in the next few days.

Thanks for taking time!
